general:
  optimizer: "cost" # "cost" or "co2" (or "peakshaving")
  start: "2015-01-01 00:00:00"
  end: "2015-12-31 23:45:00" # 23:45:00
  year: "2015"
  timebase: 15
  latitude: 50.941357
  longitude: 6.958307
  name: "VPP"
  output_file: "./Output/loadshape.csv"
  pv_data_file: "./input/pv/dwd_pv_data_2015.csv"
  slp_data_file: "./input/baseload/SLP_Amprion_15min_kW.csv"
  baseload_file_vpplib: "./input/baseload/df_S_15min.csv"
  t_0: 40

prices:
  electricity_type: "dynamic" # "dynamic" or "static" (or "static_variable_net" or "static_variable_net_and_feed-in")
  electricity: 0.25
  feed_in_tariff: 0.1
  natural_gas: 0.1
  district_heat: 0.16
  h2_sell: 0.05 # €/kWh für Verkauf ~Blauer Wasserstoff noch nicht implementiert
  # Steuern und Abgaben
  kwk_aufschlag: 0.277  # ct/kWh
  offshore_umlage: 0.816  # ct/kWh
  konzessionsabgabe: 2.39  # ct/kWh
  stromsteuer: 2.05 # ct/kWh
  mehrwertsteuer: 0.19 # 19 %
  # Netzentgelte
  netzentgelt_st: 5.77 # ct/kWh
  netzentgelt_nt: 1.73 # ct/kWh
  netzentgelt_ht: 10.34 # ct/kWh

co2_emissions:
  emission_type: "dynamic" # "dynamic" or "static"
  electricity: 429
  gas: 203
  district_heat: 100

energy_demand:
  - name: "households"
    SLP_type: "H00" #"H00" # H00, G00, G10, G20, G30...G60, L00, L10, L20
    yearly_electrical_energy_demand: 15000  # kWh
    yearly_thermal_energy_demand: 22500 # kWh
    building_type: "DE_HMF34" # 'DE_HEF33', 'DE_HEF34', 'DE_HMF33', 'DE_HMF34', 'DE_GKO34'
  - name: "business"
    SLP_type: "G00" #"H00" # H00, G00, G10, G20, G30...G60, L00, L10, L20
    yearly_electrical_energy_demand: 10000  # kWh
    yearly_thermal_energy_demand: 7000 # kWh
    building_type: "DE_GKO34"

thermal_storage:
  tes_mass: 10000
  t_max_TES: 60
  heat_exchange_power: 25
  standing_loss: 5.2e-4 # ~ 5% pro Tag
  extendable: False   # not implemented yet
  capital_cost: 200 # €/kWh # not implemented yet

grid_connection:
  grid_connection_power: 500

#components:  # not implemented yet; dynamically add components
### Optional ###
pv_systems:
  - name: "PV_1"
    pv_power: 25 # kWp
    module_lib: "SandiaMod"
    module: "Canadian_Solar_CS5P_220M___2009_"
    inverter_lib: "cecinverter"
    inverter: "Connect_Renewable_Energy__CE_4000__240V_"
    surface_tilt: 35
    surface_azimuth: 200
    modules_per_string: 4
    strings_per_inverter: 2
    temp_lib: "sapm"
    temp_model: "open_rack_glass_glass"
  # - name: "PV_2"
  #   pv_power: 35
  #   module_lib: "SandiaMod"
  #   module: "Canadian_Solar_CS5P_220M___2009_"
  #   inverter_lib: "cecinverter"
  #   inverter: "Connect_Renewable_Energy__CE_4000__240V_"
  #   surface_tilt: 30
  #   surface_azimuth: 20
  #   modules_per_string: 4
  #   strings_per_inverter: 2
  #   temp_lib: "sapm"
  #   temp_model: "open_rack_glass_glass"
  # - name: "PV_3"
  #   pv_power: 20
  #   module_lib: "SandiaMod"
  #   module: "Canadian_Solar_CS5P_220M___2009_"
  #   inverter_lib: "cecinverter"
  #   inverter: "Connect_Renewable_Energy__CE_4000__240V_"
  #   surface_tilt: 35
  #   surface_azimuth: 110
  #   modules_per_string: 4
  #   strings_per_inverter: 2
  #   temp_lib: "sapm"
  #   temp_model: "open_rack_glass_glass"

battery: # Huawei LUNA2000-200kWh-2H1
  initial_SoC: 0.5
  charge_efficiency: 0.98
  discharge_efficiency: 0.98
  max_power: 100
  capacity: 193.5 
  standing_loss: 5.2e-5 # ~ 0.5% pro Tag
  extendable: False  # not implemented yet
  capital_cost: 1000 # €/kWh  # not implemented yet

BEV:
  charger_power: 110 # kW 10*11kW Ladestationen
  efficiency: 0.9
  capacity: 800 # kWh 10*80kWh Batterien
  standing_loss: 5.2e-5 # ~ 0.5% pro Tag

heat_pumps:
  - name: "HP_Ground"
    type: "Ground" # "Ground" or "Air"
    power_el: 5
    power_th: 8
    p_min: 0.25 # Mindestleistung wenn eingeschaltet in % der Nennleistung
  - name: "HP_Air"
    type: "Air"
    power_el: 5
    power_th: 8
    p_min: 0.35 # Mindestleistung wenn eingeschaltet in % der Nennleistung

CHP:
  power: 20
  efficiency_el: 0.35
  efficiency_th: 0.45
  p_min: 0.4 # Mindestleistung wenn eingeschaltet in % der Nennleistung

gas_boiler:
  power: 20
  efficiency: 0.9
  p_min: 0.15 # Mindestleistung wenn eingeschaltet in % der Nennleistung

district_heating:
  power: 20
  efficiency: 0.95
  p_min: 0.05 # Mindestleistung wenn eingeschaltet in % der Nennleistung

electrolyzer:
  power: 20
  efficiency: 0.7
  storage_capacity: 2000 #kWh   ~ für 2000kwh ca. 3750 L bei 200bar oder 2000L bei 500bar
  storage_loss: 5.2e-5 # Annahme 0.5% pro Tag     ~ ca. 0.1 - 1 % pro Tag (Druckgasspeicherung); 1-3% pro Tag (Flüssigwasserstoffspeicherung)
  ininital_storage: 0

fuel_cell:
  power: 20
  efficiency: 0.5
